const DEFAULT_FILENAME = "Uploaded File";
const TOAST_DURATION = 4000;

const isLinkedIn =
  window.location.hostname === "linkedin.com" ||
  window.location.hostname.endsWith(".linkedin.com");


if (isLinkedIn) {
  console.log(
    "[Virtual File Renamer] Disabled on LinkedIn"
  );
} else {

  console.log(
    "[Virtual File Renamer] Content script loaded",
    chrome.runtime.id
  );


  function getExtension(filename) {
    const lastDot =
      filename.lastIndexOf(".");

    if (lastDot === -1) {
      return "";
    }

    return filename.substring(lastDot);
  }


  function createVirtualFile(file, newName) {
    return new File(
      [file],
      newName,
      {
        type: file.type,
        lastModified: file.lastModified
      }
    );
  }


  function showToast(message, type = "info") {

    const existingToast =
      document.getElementById(
        "virtual-file-renamer-toast"
      );

    if (existingToast) {
      existingToast.remove();
    }


    const toast =
      document.createElement("div");

    toast.id =
      "virtual-file-renamer-toast";

    toast.textContent = message;


    Object.assign(
      toast.style,
      {
        position: "fixed",
        right: "24px",
        bottom: "24px",
        zIndex: "2147483647",
        maxWidth: "360px",
        padding: "12px 16px",
        borderRadius: "8px",
        background: "#18181b",
        color: "#ffffff",
        fontFamily:
          "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
        fontSize: "13px",
        lineHeight: "1.4",
        boxShadow:
          "0 6px 24px rgba(0, 0, 0, 0.2)",
        opacity: "0",
        transform: "translateY(8px)",
        transition:
          "opacity 150ms ease, transform 150ms ease",
        pointerEvents: "none"
      }
    );


    if (type === "success") {
      toast.style.background = "#166534";
    }


    if (type === "warning") {
      toast.style.background = "#92400e";
    }


    document.documentElement.appendChild(
      toast
    );


    requestAnimationFrame(() => {
      toast.style.opacity = "1";
      toast.style.transform =
        "translateY(0)";
    });


    setTimeout(() => {

      toast.style.opacity = "0";
      toast.style.transform =
        "translateY(8px)";

      setTimeout(() => {
        toast.remove();
      }, 150);

    }, TOAST_DURATION);
  }


  async function getExtensionSettings() {

    try {

      return await chrome.storage.local.get([
        "enabled",
        "fileName"
      ]);

    } catch (error) {

      // The extension may have been reloaded while this page was open.
      if (
        error?.message?.includes(
          "Extension context invalidated"
        )
      ) {
        return null;
      }


      console.error(
        "[Virtual File Renamer] Failed to read settings:",
        error
      );


      return null;
    }
  }


  async function renameFiles(input) {

    if (
      !input.files ||
      input.files.length === 0
    ) {
      return;
    }


    // Ignore the synthetic change event generated by this extension.
    if (
      input.dataset.vfrProcessing === "true"
    ) {
      return;
    }


    const settings =
      await getExtensionSettings();


    if (!settings) {
      return;
    }


    if (settings.enabled === false) {
      return;
    }


    const baseName =
      settings.fileName?.trim() ||
      DEFAULT_FILENAME;


    const originalFiles =
      Array.from(input.files);


    // Avoid replacing files that already have the target name.
    const alreadyRenamed =
      originalFiles.every(file => {

        const extension =
          getExtension(file.name);

        return file.name ===
          `${baseName}${extension}`;
      });


    if (alreadyRenamed) {
      return;
    }


    const dataTransfer =
      new DataTransfer();


    const renamedFiles = [];


    for (const originalFile of originalFiles) {

      const extension =
        getExtension(
          originalFile.name
        );


      const newName =
        `${baseName}${extension}`;


      const virtualFile =
        createVirtualFile(
          originalFile,
          newName
        );


      dataTransfer.items.add(
        virtualFile
      );


      renamedFiles.push({
        original: originalFile.name,
        renamed: newName
      });
    }


    // Replace the FileList without modifying the source file on disk.
    input.dataset.vfrProcessing =
      "true";


    input.files =
      dataTransfer.files;


    // Notify the website about the updated FileList.
    input.dispatchEvent(
      new Event(
        "input",
        {
          bubbles: true
        }
      )
    );


    input.dispatchEvent(
      new Event(
        "change",
        {
          bubbles: true
        }
      )
    );


    if (renamedFiles.length === 1) {

      showToast(
        `Uploaded filename changed to "${renamedFiles[0].renamed}".`,
        "success"
      );

    } else {

      showToast(
        `${renamedFiles.length} uploaded filenames have been changed.`,
        "success"
      );
    }


    // Allow the next real user selection to be processed.
    setTimeout(() => {
      delete input.dataset.vfrProcessing;
    }, 0);
  }


  async function showFilePickerWarning() {

    const settings =
      await getExtensionSettings();


    if (
      !settings ||
      settings.enabled === false
    ) {
      return;
    }


    showToast(
      "The name of the uploaded file will be changed.",
      "warning"
    );
  }


  function observeFileInput(input) {

    if (
      input.dataset.vfrObserved === "true"
    ) {
      return;
    }


    input.dataset.vfrObserved =
      "true";


    // Show the warning before the native file picker opens.
    input.addEventListener(
      "click",
      () => {
        showFilePickerWarning();
      },
      true
    );


    input.addEventListener(
      "change",
      () => {

        if (
          input.dataset.vfrProcessing === "true"
        ) {
          return;
        }


        renameFiles(input);
      }
    );
  }


  function scanFileInputs() {

    const inputs =
      document.querySelectorAll(
        'input[type="file"]'
      );


    inputs.forEach(
      observeFileInput
    );
  }


  const observer =
    new MutationObserver(() => {
      scanFileInputs();
    });


  observer.observe(
    document.documentElement,
    {
      childList: true,
      subtree: true
    }
  );


  scanFileInputs();


  console.log(
    "[Virtual File Renamer] Initial scan complete"
  );
}